ALTER TABLE application ADD COLUMN logo VARCHAR(100) DEFAULT NULL;
ALTER TABLE application ADD COLUMN district VARCHAR(100) DEFAULT NULL;
ALTER TABLE application ADD COLUMN leader VARCHAR(100) DEFAULT NULL;